# Generated by Django 3.1 on 2021-02-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
