# Generated by Django 3.1 on 2021-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='binaryPhoto',
            field=models.BinaryField(blank=True),
        ),
    ]
